version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_capsula
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre123
      POSTGRES_DB: capsula_tempo_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: fastapi_capsula
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes: 
      - .:/app
    
volumes:
  pgdata:
